### PR TITLE
Modify translations

### PR DESCRIPTION
**Pull request by morizotter**
When Japanese is showed, the text layout collapsed like below. I fixed them as possible as I can.

## Collapsed text layouts

side1

side2

footer

## URL exposed

My translation failed to link appropriately like below. I change these parts of translation in this pull request. But I don't know if this is fixed.

url

### CODE REVIEW

**Comment by autopulated** [comment]
Ah! the `more:` URLs shouldn't be in these translations:

fact-supporter-1, fact-supporter-2, fact-supporter-3, fact-api-1

I've fixed that here: #87 for the other translations.

**Comment by morizotter** [comment]
Fixed that parts!

**Comment by autopulated** [comment]
Looks good!

**Comment by autopulated** [comment]
screen shot 2015-04-11 at 13 18 27

:+1:

**Pull request merged**
