### PR TITLE
Add zh-CN translation

### PR DESCRIPTION
**Pull request by Junyih**
Started with login widget

### CODE REVIEW

**Comment by Junyih** [comment]
pushed to wrong branch..

**Comment by autopulated** [comment]
Great start, thanks!

I will merge to the testing branch and then production later.

**Comment by autopulated** [comment]
Screenshot from testing, looking good!

screen shot 2015-04-21 at 22 38 40

**Comment by Junyih** [comment]
Great! i feel happy[?]

**Pull request merged**
