### PR TITLE
Create ro-RO.l20n

### PR DESCRIPTION
**Pull request by valentineni**
Coggle translations for Romanian version, unfinished,  work in progress.

### CODE REVIEW

**Comment by autopulated** [comment]
Thanks for contributing! 😄 

For us to add this on the site we need you to agree to the contributor agreement here: https://www.clahub.com/agreements/Coggle/coggle-translations (so that we have the permission necessary to use your translations).

It looks like you've used the Russian file as the base translations – which is OK as that file is very up-to-date – but for future reference the en-US.l20n file is the best one to base things on.

**Comment by valentineni** [comment]
Thanks for the acceptance of Romanian translation, even if is not complete.
I'm enchanted with coggle and the next few days I will work on finishing
the translation. Actually I use both Russian and English files as source,
because I'm not very good at English.
Best regards

Pe 20.03.2017 18:41, "James Crosby" <notifications@github.com> a scris:

**Comment by autopulated** [comment]
Thanks, looks good so far!

**Comment by autopulated** [comment]
https://coggle.it/home?lang=ro-RO 😀

**Pull request merged**
