### PR TITLE
Create ja jp

### PR DESCRIPTION
**Pull request by morizotter**
I created ja-JP.l20n file and translated front page content.

### CODE REVIEW

**Comment by autopulated** [comment]
Great! Thanks for contributing. :+1:  

I'll merge this to the testing branches and then to the live site later.

**Comment by autopulated** [comment]
Ah, just noticed you haven't completed the contributor agreement – please do that so we can use your translations! You can find it here: https://www.clahub.com/agreements/Coggle/translations

**Comment by morizotter** [comment]
I tried to submit contributor agreement but failed everytime with this message.

**Comment by autopulated** [comment]
Ah sorry! I think that should be fixed now. It looks like CLAhub's access token was invalid.

**Comment by morizotter** [comment]
I tried several times but I still cannot submit contributor agreement. Are there any other errors?

**Comment by autopulated** [comment]
In that case it looks like it might have been caused by renaming the repository.

I've set up an identical new one for "Coggle/coggle-translations" here: https://www.clahub.com/agreements/Coggle/coggle-translations 

(the old one can still be found at https://www.clahub.com/agreements/Coggle/translations)

Hopefully this works!

**Comment by morizotter** [comment]
I succeed to  submit in Coggle/coggle-translations!

**Comment by autopulated** [comment]
Ok great! Sorry for the confusion there.

**Pull request merged**
