### PR TITLE
Translate list and hints

### PR DESCRIPTION
**Pull request by morizotter**
Translate list and hints.

### CODE REVIEW

**Comment by autopulated** [comment]
Also looking good!

I have one question:
"sign up using google" should maybe be something like "GOOGLE に登録", (it looks like google uses that themselves).

I don't know if that makes any sense, because I'm relying on automated translation, and navigating google's website in Japanese was a bit tricky ;) but it feels like "USING" should be translated too?

**Comment by autopulated** [comment]
For context here's an image of where that appears: 
screen shot 2015-04-07 at 21 00 51

**Comment by morizotter** [comment]
I feel that "USING" is also be translated as you think. But it was a little difficult and original English word make sense so I didn't translate that part.

"GOOGLEに登録" means like "sign up in GOOGLE". And in Japanese context, the words order is different like these below.







I will think other better way later.

**Comment by autopulated** [comment]
Ah OK – if it makes sense you could drop the second line completely. I *think* it would also be possible to swap the small text so it's above the large text, if that's necessary... :thought_balloon:

**Pull request merged**
