### PR TITLE
improving new language de-DE

### PR DESCRIPTION
**Pull request by matthiasburger**
added source language-file for German

### CODE REVIEW

**Comment by matthiasburger** [comment]
sorry guys for creating two pull request instead of one.. it was late in the night

**Comment by autopulated** [comment]
That's ok, thanks for contributing! I'll test and deploy this in the next few days.

**Comment by matthiasburger** [comment]
great! But I still need some time to complete the whole translation.

**Comment by autopulated** [comment]
Just create new PRs with more lines translated, and we will update the site :)

**Pull request merged**
