### PR TITLE
zh-CN translation: help, tutorial, and Coggle Orginazitions

### PR DESCRIPTION
**Pull request by Junyih**

### CODE REVIEW

**Comment by Junyih** [comment]
I think i have finished the basic translation  of "help & tutorial & control"

**Comment by autopulated** [comment]
Looks good! :smiley: 

I will test again, and if things go well merge to the live site later.

**Comment by Junyih** [comment]
Hi James,

How can i test it, before submitting the changes to master branch?

//Junyi

**Comment by autopulated** [comment]
Unfortunately that isn't easily possible at the moment. Submitting untested changes to the master branch is OK – we merge to the testing and then to the production branch before things go live on the site.

**Pull request merged**
